export const imageGallery = [
  {
    id: 1,
    imgUrl: "https://picsum.photos/200/300?random=1",
    yearClicked: 2014,
    imgDetails: "Beautiful landscape with mountains.",
  },
  {
    id: 2,
    imgUrl: "https://picsum.photos/200/300?random=2",
    yearClicked: 2013,
    imgDetails: "Colorful abstract art in the city.",
  },
  {
    id: 3,
    imgUrl: "https://picsum.photos/200/300?random=3",
    yearClicked: 2012,
    imgDetails: "Serene beach with golden sands.",
  },
  {
    id: 4,
    imgUrl: "https://picsum.photos/200/300?random=4",
    yearClicked: 2014,
    imgDetails: "Majestic mountain range with a clear sky.",
  },
  {
    id: 5,
    imgUrl: "https://picsum.photos/200/300?random=5",
    yearClicked: 2013,
    imgDetails: "Aerial view of a vibrant city at dusk.",
  },
  {
    id: 6,
    imgUrl: "https://picsum.photos/200/300?random=6",
    yearClicked: 2012,
    imgDetails: "Tranquil lake surrounded by lush greenery.",
  },
  {
    id: 7,
    imgUrl: "https://picsum.photos/200/300?random=7",
    yearClicked: 2014,
    imgDetails: "Spectacular sunrise over the ocean horizon.",
  },
  {
    id: 8,
    imgUrl: "https://picsum.photos/200/300?random=8",
    yearClicked: 2013,
    imgDetails: "Modern architecture with futuristic design.",
  },
  {
    id: 9,
    imgUrl: "https://picsum.photos/200/300?random=9",
    yearClicked: 2012,
    imgDetails: "Enchanting forest with sunlight filtering through the leaves.",
  },
  {
    id: 10,
    imgUrl: "https://picsum.photos/200/300?random=10",
    yearClicked: 2014,
    imgDetails: "A charming village with cobblestone streets.",
  },
  {
    id: 11,
    imgUrl: "https://picsum.photos/200/300?random=11",
    yearClicked: 2013,
    imgDetails: "Dynamic cityscape with skyscrapers and city lights.",
  },
  {
    id: 12,
    imgUrl: "https://picsum.photos/200/300?random=12",
    yearClicked: 2012,
    imgDetails: "Tranquil riverside scene with reflections in the water.",
  },
  {
    id: 13,
    imgUrl: "https://picsum.photos/200/300?random=13",
    yearClicked: 2014,
    imgDetails: "Snow-covered mountain peaks against a blue sky.",
  },
  {
    id: 14,
    imgUrl: "https://picsum.photos/200/300?random=14",
    yearClicked: 2013,
    imgDetails: "Lively street market with diverse stalls and colors.",
  },
  {
    id: 15,
    imgUrl: "https://picsum.photos/200/300?random=15",
    yearClicked: 2012,
    imgDetails: "Agricultural fields under a golden sunset.",
  },
  {
    id: 16,
    imgUrl: "https://picsum.photos/200/300?random=16",
    yearClicked: 2014,
    imgDetails: "Mystical forest with fog and ancient trees.",
  },
  {
    id: 17,
    imgUrl: "https://picsum.photos/200/300?random=17",
    yearClicked: 2013,
    imgDetails: "Urban park with a mix of nature and modern structures.",
  },
  {
    id: 18,
    imgUrl: "https://picsum.photos/200/300?random=18",
    yearClicked: 2012,
    imgDetails: "Cozy coastal town with traditional architecture.",
  },
  {
    id: 19,
    imgUrl: "https://picsum.photos/200/300?random=19",
    yearClicked: 2014,
    imgDetails: "Surreal landscape with floating islands in the sky.",
  },
  {
    id: 20,
    imgUrl: "https://picsum.photos/200/300?random=20",
    yearClicked: 2013,
    imgDetails: "Rural countryside with rolling hills and farmsteads.",
  },
  {
    id: 21,
    imgUrl: "https://picsum.photos/200/300?random=21",
    yearClicked: 2012,
    imgDetails: "Quaint village surrounded by dense forests.",
  },
  {
    id: 22,
    imgUrl: "https://picsum.photos/200/300?random=22",
    yearClicked: 2014,
    imgDetails: "Panoramic view of a vibrant city skyline.",
  },
  {
    id: 23,
    imgUrl: "https://picsum.photos/200/300?random=23",
    yearClicked: 2013,
    imgDetails: "Historic architecture with intricate details.",
  },
  {
    id: 24,
    imgUrl: "https://picsum.photos/200/300?random=24",
    yearClicked: 2012,
    imgDetails: "Breathtaking desert landscape with sand dunes.",
  },
  {
    id: 25,
    imgUrl: "https://picsum.photos/200/300?random=25",
    yearClicked: 2014,
    imgDetails: "Lively city street with bustling activity.",
  },
  {
    id: 26,
    imgUrl: "https://picsum.photos/200/300?random=26",
    yearClicked: 2013,
    imgDetails: "Sunset over a tranquil rural lake setting.",
  },
  {
    id: 27,
    imgUrl: "https://picsum.photos/200/300?random=27",
    yearClicked: 2012,
    imgDetails: "Futuristic cityscape with high-tech architecture.",
  },
  {
    id: 28,
    imgUrl: "https://picsum.photos/200/300?random=28",
    yearClicked: 2014,
    imgDetails: "Snowy mountain peaks against a pink twilight sky.",
  },
  {
    id: 29,
    imgUrl: "https://picsum.photos/200/300?random=29",
    yearClicked: 2013,
    imgDetails: "Cultural festival with vibrant costumes and music.",
  },
  {
    id: 30,
    imgUrl: "https://picsum.photos/200/300?random=30",
    yearClicked: 2012,
    imgDetails: "Peaceful countryside with a traditional windmill.",
  },
  {
    id: 31,
    imgUrl: "https://picsum.photos/200/300?random=31",
    yearClicked: 2013,
    imgDetails: "Majestic waterfall in a pristine natural setting.",
  },
  {
    id: 32,
    imgUrl: "https://picsum.photos/200/300?random=32",
    yearClicked: 2013,
    imgDetails: "Busy urban intersection with city traffic.",
  },
  {
    id: 33,
    imgUrl: "https://picsum.photos/200/300?random=33",
    yearClicked: 2012,
    imgDetails: "Lush greenery in a tropical rainforest.",
  },
  {
    id: 34,
    imgUrl: "https://picsum.photos/200/300?random=34",
    yearClicked: 2012,
    imgDetails: "Charming European town square with cafes.",
  },
  {
    id: 35,
    imgUrl: "https://picsum.photos/200/300?random=35",
    yearClicked: 2014,
    imgDetails: "Dynamic cityscape with modern skyscrapers.",
  },
  {
    id: 36,
    imgUrl: "https://picsum.photos/200/300?random=36",
    yearClicked: 2014,
    imgDetails: "Picturesque coastal scene with cliffs and waves.",
  },
  {
    id: 37,
    imgUrl: "https://picsum.photos/200/300?random=37",
    yearClicked: 2014,
    imgDetails: "Urban park with a mix of nature and recreational spaces.",
  },
  {
    id: 38,
    imgUrl: "https://picsum.photos/200/300?random=38",
    yearClicked: 2012,
    imgDetails: "Traditional Japanese garden with a serene pond.",
  },
  {
    id: 39,
    imgUrl: "https://picsum.photos/200/300?random=39",
    yearClicked: 2013,
    imgDetails: "Enchanting forest with sunlight peeking through trees.",
  },
  {
    id: 40,
    imgUrl: "https://picsum.photos/200/300?random=40",
    yearClicked: 2014,
    imgDetails: "Urban skyline at night with city lights.",
  },
  {
    id: 41,
    imgUrl: "https://picsum.photos/200/300?random=41",
    yearClicked: 2012,
    imgDetails: "Charming village nestled in the countryside.",
  },
  {
    id: 42,
    imgUrl: "https://picsum.photos/200/300?random=42",
    yearClicked: 2013,
    imgDetails: "Vibrant market with street vendors and lively colors.",
  },
  {
    id: 43,
    imgUrl: "https://picsum.photos/200/300?random=43",
    yearClicked: 2014,
    imgDetails: "Urban skyline at night with city lights.",
  },
  {
    id: 44,
    imgUrl: "https://picsum.photos/200/300?random=44",
    yearClicked: 2012,
    imgDetails: "Charming village nestled in the countryside.",
  },
  {
    id: 45,
    imgUrl: "https://picsum.photos/200/300?random=45",
    yearClicked: 2013,
    imgDetails: "Vibrant market with street vendors and lively colors.",
  },
  {
    id: 46,
    imgUrl: "https://picsum.photos/200/300?random=46",
    yearClicked: 2014,
    imgDetails: "Urban skyline at night with city lights.",
  },
  {
    id: 47,
    imgUrl: "https://picsum.photos/200/300?random=47",
    yearClicked: 2012,
    imgDetails: "Charming village nestled in the countryside.",
  },
  {
    id: 48,
    imgUrl: "https://picsum.photos/200/300?random=48",
    yearClicked: 2013,
    imgDetails: "Vibrant market with street vendors and lively colors.",
  },
  {
    id: 49,
    imgUrl: "https://picsum.photos/200/300?random=49",
    yearClicked: 2014,
    imgDetails: "Urban skyline at night with city lights.",
  },
  {
    id: 50,
    imgUrl: "https://picsum.photos/200/300?random=50",
    yearClicked: 2012,
    imgDetails: "Charming village nestled in the countryside.",
  },
  {
    id: 51,
    imgUrl: "https://picsum.photos/200/300?random=51",
    yearClicked: 2013,
    imgDetails: "Vibrant market with street vendors and lively colors.",
  },
  {
    id: 52,
    imgUrl: "https://picsum.photos/200/300?random=52",
    yearClicked: 2014,
    imgDetails: "Urban skyline at night with city lights.",
  },
  {
    id: 53,
    imgUrl: "https://picsum.photos/200/300?random=53",
    yearClicked: 2012,
    imgDetails: "Charming village nestled in the countryside.",
  },
  {
    id: 54,
    imgUrl: "https://picsum.photos/200/300?random=54",
    yearClicked: 2013,
    imgDetails: "Vibrant market with street vendors and lively colors.",
  },
  {
    id: 55,
    imgUrl: "https://picsum.photos/200/300?random=55",
    yearClicked: 2014,
    imgDetails: "Urban skyline at night with city lights.",
  },
  {
    id: 56,
    imgUrl: "https://picsum.photos/200/300?random=56",
    yearClicked: 2012,
    imgDetails: "Charming village nestled in the countryside.",
  },
  {
    id: 57,
    imgUrl: "https://picsum.photos/200/300?random=57",
    yearClicked: 2013,
    imgDetails: "Vibrant market with street vendors and lively colors.",
  },
  {
    id: 58,
    imgUrl: "https://picsum.photos/200/300?random=58",
    yearClicked: 2014,
    imgDetails: "Urban skyline at night with city lights.",
  },
  {
    id: 59,
    imgUrl: "https://picsum.photos/200/300?random=59",
    yearClicked: 2012,
    imgDetails: "Charming village nestled in the countryside.",
  },
  {
    id: 60,
    imgUrl: "https://picsum.photos/200/300?random=60",
    yearClicked: 2013,
    imgDetails: "Vibrant market with street vendors and lively colors.",
  },
];
